#!/bin/zsh

git checkout release
git merge master
git push
git checkout master

if perl < /dev/null > /dev/null 2>&1 ;
then

	if perl -i -pe 's/(version": "[0-9]+\.[0-9]+\.)([0-9]+)/{$1.(1+$2)}/e' package.json ; then
		echo -e '\nVersion updated: package.json'
		echo ' '
	else
		echo -e '\nError updating package.json\n'
		exit 1
	fi

else echo "Cannot find perl. Please manually increment the Stardate"
	exit 1
fi

git add package.json
git commit -m version
git push
