#!/bin/bash

echo ''
echo '--------------------------'
echo "--___RE-TAGGING: ${1}"
echo '--------------------------'
echo ''

git tag -d ${1}
git push origin :refs/tags/${1}
git tag -a ${1} -m 'Auto-tagged'
git push --tags

